export const bannedWords = [
    'ladyboy',
    'กระเทย',
    'กะเทย',
    'singlemom',
    'single mom',
    'singlemother',
    'single mom',
    'เกย์',
    'ชายแท้',
    'สาวสอง',
    'gay',
    'transgender',
    'trangender',
    'lgbt',
    'lgtv',
    'สาว2',
    'เลี้ยงเดี่ยว',
    'notgirl',
    'notagirl',
    'ใช่ผู้หญิง',
    'ใช่ผญ',
    '🏳️‍🌈',
    '🌈',
    'ไม่ใช่ผญ',
    'สาวส',
    '🏳️‍⚧️',
    'ข้ามเพศ',
    'แปลงเพศ',
    'notwoman',
    'notawoman',
    'ประเภท2',
    'ประเภทสอง',
    'ลูกติด',
    'trans',
    'ตุ๊ด',
    'ไม่ใช่ญแท้',
    '🐍',
    'นมงู',
    'ทราน',
    'มีงู',
    'ไม่แปลง',
    'ว2',
    'เปย์',
    'notarealwoman',
    'notrealwoman',
    'notrealgirl',
    'notarealgirl',
    'ไม่หญิง',
    'femboy',
    'feminineboy',
    'notlady',
    'notladies',
    'มีลูก',
    'ไม่ใช่ผญ',
    'muslim',
    'มุสลิม',
    // 'fat',
    // 'อ้วน',
    'แม่ลูก',
]

export const acceptedWords = [
    'notaladyboy',
    'notladyboy',
    'ไม่ใช่สาวสอง',
    'ไม่ใช่กระเทย',
    'เป็นผู้หญิง',
]

export const bannedSex = ['gay', 'queer', 'questioning']
